/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DesignRouteImport } from './routes/design'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignUpRouteImport } from './routes/signUp'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppProgrammingRouteImport } from './routes/app.programming'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTrainingRouteImport } from './routes/app.training'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppHistoryBlockIdRouteImport } from './routes/app.history.$blockId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppProgrammingRoute = AppProgrammingRouteImport.update({
  id: '/programming',
  path: '/programming',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryBlockIdRoute = AppHistoryBlockIdRouteImport.update({
  id: '/$blockId',
  path: '/$blockId',
  getParentRoute: () => AppHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/signUp': typeof SignUpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRouteWithChildren
  '/app/programming': typeof AppProgrammingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/training': typeof AppTrainingRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/history/$blockId': typeof AppHistoryBlockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/signUp': typeof SignUpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRouteWithChildren
  '/app/programming': typeof AppProgrammingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/training': typeof AppTrainingRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/history/$blockId': typeof AppHistoryBlockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/signUp': typeof SignUpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRouteWithChildren
  '/app/programming': typeof AppProgrammingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/training': typeof AppTrainingRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/history/$blockId': typeof AppHistoryBlockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/design'
    | '/login'
    | '/signUp'
    | '/app/analytics'
    | '/app/history'
    | '/app/programming'
    | '/app/settings'
    | '/app/training'
    | '/app/'
    | '/api/auth/$'
    | '/app/history/$blockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/login'
    | '/signUp'
    | '/app/analytics'
    | '/app/history'
    | '/app/programming'
    | '/app/settings'
    | '/app/training'
    | '/app'
    | '/api/auth/$'
    | '/app/history/$blockId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/design'
    | '/login'
    | '/signUp'
    | '/app/analytics'
    | '/app/history'
    | '/app/programming'
    | '/app/settings'
    | '/app/training'
    | '/app/'
    | '/api/auth/$'
    | '/app/history/$blockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DesignRoute: typeof DesignRoute
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/programming': {
      id: '/app/programming'
      path: '/programming'
      fullPath: '/app/programming'
      preLoaderRoute: typeof AppProgrammingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history/$blockId': {
      id: '/app/history/$blockId'
      path: '/$blockId'
      fullPath: '/app/history/$blockId'
      preLoaderRoute: typeof AppHistoryBlockIdRouteImport
      parentRoute: typeof AppHistoryRoute
    }
  }
}

interface AppHistoryRouteChildren {
  AppHistoryBlockIdRoute: typeof AppHistoryBlockIdRoute
}

const AppHistoryRouteChildren: AppHistoryRouteChildren = {
  AppHistoryBlockIdRoute: AppHistoryBlockIdRoute,
}

const AppHistoryRouteWithChildren = AppHistoryRoute._addFileChildren(
  AppHistoryRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppHistoryRoute: typeof AppHistoryRouteWithChildren
  AppProgrammingRoute: typeof AppProgrammingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppHistoryRoute: AppHistoryRouteWithChildren,
  AppProgrammingRoute: AppProgrammingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DesignRoute: DesignRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
